version: "3"

services:
  app:
    build: # use image is built from Dockerfile
      context: .
      dockerfile: docker/ruby/Dockerfile
    # Run entrypoint after db service ready
    # command: docker/entrypoint.sh
    volumes:
      - .:/app # mount data beetwen host and container
      - bundle:/bundle
    ports: # left (host port), right (expose port)
      - 3000:3000
    env_file: .env # list environments use file
    stdin_open: true
    tty: true
volumes:
  db-data:
  bundle:
  redis-data:
